<a href="https://colab.research.google.com/github/Naisha31/Income-Prediction-Model/blob/main/Income_prediction_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/adult.csv")
df.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

In [ ]:
df.dtypes

NameError: name 'df' is not defined

In [ ]:
df.shape

(32561, 15)

In [ ]:
df.replace('?', np.nan, inplace=True)

In [ ]:
df.describe(include='all')

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
count,32561.000000,30725,3.256100e+04,32561,32561.000000,32561,30718,32561,32561,32561,32561.000000,32561.000000,32561.000000,31978,32561
unique,NaN,8,NaN,16,NaN,7,14,6,5,2,NaN,NaN,NaN,41,2
top,NaN,Private,NaN,HS-grad,NaN,Married-civ-spouse,Prof-specialty,Husband,White,Male,NaN,NaN,NaN,United-States,<=50K
freq,NaN,22696,NaN,10501,NaN,14976,4140,13193,27816,21790,NaN,NaN,NaN,29170,24720
mean,38.581647,NaN,1.897784e+05,NaN,10.080679,NaN,NaN,NaN,NaN,NaN,1077.648844,87.303830,40.437456,NaN,NaN
std,13.640433,NaN,1.055500e+05,NaN,2.572720,NaN,NaN,NaN,NaN,NaN,7385.292085,402.960219,12.347429,NaN,NaN
min,17.000000,NaN,1.228500e+04,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,1.000000,NaN,NaN
25%,28.000000,NaN,1.178270e+05,NaN,9.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,40.000000,NaN,NaN
50%,37.000000,NaN,1.783560e+05,NaN,10.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,40.000000,NaN,NaN
75%,48.000000,NaN,2.370510e+05,NaN,12.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,45.000000,NaN,NaN
max,90.000000,NaN,1.484705e+06,NaN,16.000000,NaN,NaN,NaN,NaN,NaN,99999.000000,4356.000000,99.000000,NaN,NaN

In [ ]:
df.isnull().sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education.num        0
marital.status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital.gain         0
capital.loss         0
hours.per.week       0
native.country     583
income               0
dtype: int64

In [ ]:
df["workclass"].replace(np.nan, "Private", inplace=True)
df["occupation"].replace(np.nan, "Prof-specialty", inplace=True)
df["native.country"].replace(np.nan, "United-States", inplace=True)

In [ ]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
sex               0
capital.gain      0
capital.loss      0
hours.per.week    0
native.country    0
income            0
dtype: int64

In [ ]:
df[df.duplicated()]

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
8453,25,Private,308144,Bachelors,13,Never-married,Craft-repair,Not-in-family,White,Male,0,0,40,Mexico,<=50K
8645,90,Private,52386,Some-college,10,Never-married,Other-service,Not-in-family,Asian-Pac-Islander,Male,0,0,35,United-States,<=50K
12202,21,Private,250051,Some-college,10,Never-married,Prof-specialty,Own-child,White,Female,0,0,10,United-States,<=50K
14346,20,Private,107658,Some-college,10,Never-married,Tech-support,Not-in-family,White,Female,0,0,10,United-States,<=50K
15603,25,Private,195994,1st-4th,2,Never-married,Priv-house-serv,Not-in-family,White,Female,0,0,40,Guatemala,<=50K
17344,21,Private,243368,Preschool,1,Never-married,Farming-fishing,Not-in-family,White,Male,0,0,50,Mexico,<=50K
19067,46,Private,173243,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
20388,30,Private,144593,HS-grad,9,Never-married,Other-service,Not-in-family,Black,Male,0,0,40,United-States,<=50K
20507,19,Private,97261,HS-grad,9,Never-married,Farming-fishing,Not-in-family,White,Male,0,0,40,United-States,<=50K
22783,19,Private,138153,Some-college,10,Never-married,Adm-clerical,Own-child,White,Female,0,0,10,United-States,<=50K
22934,19,Private,146679,Some-college,10,Never-married,Exec-managerial,Own-child,Black,Male,0,0,30,United-States,<=50K
23276,49,Private,31267,7th-8th,4,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
23660,25,Private,195994,1st-4th,2,Never-married,Priv-house-serv,Not-in-family,White,Female,0,0,40,Guatemala,<=50K
23720,44,Private,367749,Bachelors,13,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,45,Mexico,<=50K
23827,49,Self-emp-not-inc,43479,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
26738,23,Private,240137,5th-6th,3,Never-married,Handlers-cleaners,Not-in-family,White,Male,0,0,55,Mexico,<=50K
27133,28,Private,274679,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,50,United-States,<=50K
28796,27,Private,255582,HS-grad,9,Never-married,Machine-op-inspct,Not-in-family,White,Female,0,0,40,United-States,<=50K
29051,42,Private,204235,Some-college,10,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,>50K
29334,39,Private,30916,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
29604,38,Private,207202,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,48,United-States,>50K
31060,46,Private,133616,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32065,19,Private,251579,Some-college,10,Never-married,Other-service,Own-child,White,Male,0,0,14,United-States,<=50K
32419,35,Private,379959,HS-grad,9,Divorced,Other-service,Not-in-family,White,Female,0,0,40,United-States,<=50K

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df['workclass'].value_counts()

workclass
Private             24509
Self-emp-not-inc     2540
Local-gov            2093
State-gov            1298
Self-emp-inc         1116
Federal-gov           960
Without-pay            14
Never-worked            7
Name: count, dtype: int64

In [ ]:
df['education'].value_counts()

education
HS-grad         10494
Some-college     7282
Bachelors        5353
Masters          1722
Assoc-voc        1382
11th             1175
Assoc-acdm       1067
10th              933
7th-8th           645
Prof-school       576
9th               514
12th              433
Doctorate         413
5th-6th           332
1st-4th           166
Preschool          50
Name: count, dtype: int64

In [ ]:
df['marital.status'].value_counts()

marital.status
Married-civ-spouse       14970
Never-married            10667
Divorced                  4441
Separated                 1025
Widowed                    993
Married-spouse-absent      418
Married-AF-spouse           23
Name: count, dtype: int64

In [ ]:
df['occupation'].value_counts()

occupation
Prof-specialty       5979
Craft-repair         4094
Exec-managerial      4065
Adm-clerical         3768
Sales                3650
Other-service        3291
Machine-op-inspct    2000
Transport-moving     1597
Handlers-cleaners    1369
Farming-fishing       992
Tech-support          927
Protective-serv       649
Priv-house-serv       147
Armed-Forces            9
Name: count, dtype: int64

In [ ]:
df['relationship'].value_counts()

relationship
Husband           13187
Not-in-family      8292
Own-child          5064
Unmarried          3445
Wife               1568
Other-relative      981
Name: count, dtype: int64

In [ ]:
df['race'].value_counts()

race
White                 27795
Black                  3122
Asian-Pac-Islander     1038
Amer-Indian-Eskimo      311
Other                   271
Name: count, dtype: int64

In [ ]:
df['sex'].value_counts()

sex
Male      21775
Female    10762
Name: count, dtype: int64

In [ ]:
df['native.country'].value_counts()

native.country
United-States                 29735
Mexico                          639
Philippines                     198
Germany                         137
Canada                          121
Puerto-Rico                     114
El-Salvador                     106
India                           100
Cuba                             95
England                          90
Jamaica                          81
South                            80
China                            75
Italy                            73
Dominican-Republic               70
Vietnam                          67
Guatemala                        62
Japan                            62
Poland                           60
Columbia                         59
Taiwan                           51
Haiti                            44
Iran                             43
Portugal                         37
Nicaragua                        34
Peru                             31
Greece                           29
France                           29
Ecuador                          28
Ireland                          24
Hong                             20
Trinadad&Tobago                  19
Cambodia                         19
Thailand                         18
Laos                             18
Yugoslavia                       16
Outlying-US(Guam-USVI-etc)       14
Hungary                          13
Honduras                         13
Scotland                         12
Holand-Netherlands                1
Name: count, dtype: int64

In [ ]:
df['relationship'].value_counts()

relationship
Husband           13187
Not-in-family      8292
Own-child          5064
Unmarried          3445
Wife               1568
Other-relative      981
Name: count, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

le = LabelEncoder()
le.fit(df['income'])

NameError: name 'df' is not defined

In [ ]:
le.classes_

array(['<=50K', '>50K'], dtype=object)

In [ ]:
df['income']=le.transform(df['income'])

In [ ]:
le.fit(df['education'])

LabelEncoder()

In [ ]:
le.classes_

array(['10th', '11th', '12th', '1st-4th', '5th-6th', '7th-8th', '9th',
       'Assoc-acdm', 'Assoc-voc', 'Bachelors', 'Doctorate', 'HS-grad',
       'Masters', 'Preschool', 'Prof-school', 'Some-college'],
      dtype=object)

In [ ]:
df['education']=le.transform(df['education'])

In [ ]:
workclass=pd.get_dummies(df['workclass'])
df=pd.concat([df,workclass],axis=1)
df.drop(['workclass'],axis=1,inplace=True)

marital_status=pd.get_dummies(df['marital.status'])
df=pd.concat([df,marital_status],axis=1)
df.drop(['marital.status'],axis=1,inplace=True)

relationship=pd.get_dummies(df['relationship'])
df=pd.concat([df,relationship],axis=1)
df.drop(['relationship'],axis=1,inplace=True)

sex=pd.get_dummies(df['sex'])
df=pd.concat([df,sex],axis=1)
df.drop(['sex'],axis=1,inplace=True)

race=pd.get_dummies(df['race'])
df=pd.concat([df,race],axis=1)
df.drop(['race'],axis=1,inplace=True)

occupation=pd.get_dummies(df['occupation'])
df=pd.concat([df,occupation],axis=1)
df.drop(['occupation'],axis=1,inplace=True)

native_country=pd.get_dummies(df['native.country'])
df=pd.concat([df,native_country],axis=1)
df.drop(['native.country'],axis=1,inplace=True)

df

,age,fnlwgt,education,education.num,capital.gain,capital.loss,hours.per.week,income,Federal-gov,Local-gov,...,Portugal,Puerto-Rico,Scotland,South,Taiwan,Thailand,Trinadad&Tobago,United-States,Vietnam,Yugoslavia
0,90,77053,11,9,0,4356,40,0,False,False,...,False,False,False,False,False,False,False,True,False,False
1,82,132870,11,9,0,4356,18,0,False,False,...,False,False,False,False,False,False,False,True,False,False
2,66,186061,15,10,0,4356,40,0,False,False,...,False,False,False,False,False,False,False,True,False,False
3,54,140359,5,4,0,3900,40,0,False,False,...,False,False,False,False,False,False,False,True,False,False
4,41,264663,15,10,0,3900,40,0,False,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,22,310152,15,10,0,0,40,0,False,False,...,False,False,False,False,False,False,False,True,False,False
32557,27,257302,7,12,0,0,38,0,False,False,...,False,False,False,False,False,False,False,True,False,False
32558,40,154374,11,9,0,0,40,1,False,False,...,False,False,False,False,False,False,False,True,False,False
32559,58,151910,11,9,0,0,40,0,False,False,...,False,False,False,False,False,False,False,True,False,False
32560,22,201490,11,9,0,0,20,0,False,False,...,False,False,False,False,False,False,False,True,False,False

In [ ]:
X =df.drop(['income'],axis=1)
y =df['income']

In [ ]:
education=X['education']
X.drop(['education'],axis=1,inplace=True)
X=pd.concat([X,education],axis=1)

In [ ]:
X

,age,fnlwgt,education.num,capital.gain,capital.loss,hours.per.week,Federal-gov,Local-gov,Never-worked,Private,...,Puerto-Rico,Scotland,South,Taiwan,Thailand,Trinadad&Tobago,United-States,Vietnam,Yugoslavia,education
0,90,77053,9,0,4356,40,False,False,False,True,...,False,False,False,False,False,False,True,False,False,11
1,82,132870,9,0,4356,18,False,False,False,True,...,False,False,False,False,False,False,True,False,False,11
2,66,186061,10,0,4356,40,False,False,False,True,...,False,False,False,False,False,False,True,False,False,15
3,54,140359,4,0,3900,40,False,False,False,True,...,False,False,False,False,False,False,True,False,False,5
4,41,264663,10,0,3900,40,False,False,False,True,...,False,False,False,False,False,False,True,False,False,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,22,310152,10,0,0,40,False,False,False,True,...,False,False,False,False,False,False,True,False,False,15
32557,27,257302,12,0,0,38,False,False,False,True,...,False,False,False,False,False,False,True,False,False,7
32558,40,154374,9,0,0,40,False,False,False,True,...,False,False,False,False,False,False,True,False,False,11
32559,58,151910,9,0,0,40,False,False,False,True,...,False,False,False,False,False,False,True,False,False,11
32560,22,201490,9,0,0,20,False,False,False,True,...,False,False,False,False,False,False,True,False,False,11

In [ ]:
y

0        0
1        0
2        0
3        0
4        0
        ..
32556    0
32557    0
32558    1
32559    0
32560    0
Name: income, Length: 32537, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=56)-

In [ ]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train.iloc[:,:6] = sc.fit_transform(X_train.iloc[:,:6] )
X_test.iloc[:,:6]  = sc.transform(X_test.iloc[:,:6] )

In [ ]:
X_train

,age,fnlwgt,education.num,capital.gain,capital.loss,hours.per.week,Federal-gov,Local-gov,Never-worked,Private,...,Puerto-Rico,Scotland,South,Taiwan,Thailand,Trinadad&Tobago,United-States,Vietnam,Yugoslavia,education
19595,-1.364315,0.466021,-1.198259,-0.146694,-0.21647,-0.036395,False,False,False,True,...,False,False,False,False,False,False,True,False,False,1
25010,-0.924417,1.836581,-0.809958,-0.146694,-0.21647,-0.036395,False,False,False,True,...,False,False,False,False,False,False,True,False,False,2
19325,-0.484518,0.529450,-0.421657,-0.146694,-0.21647,1.585026,False,False,False,True,...,False,False,False,False,False,False,True,False,False,11
118,3.254619,-0.344274,1.131545,-0.146694,5.70024,1.179671,False,False,False,False,...,False,False,False,False,False,False,True,False,False,9
19771,0.028697,-0.373254,0.743245,-0.146694,-0.21647,-0.036395,False,False,False,True,...,False,False,False,False,False,False,True,False,False,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25850,-0.924417,0.795002,-0.033357,-0.146694,-0.21647,-0.036395,False,True,False,False,...,False,False,False,False,False,False,False,False,False,15
13733,-0.411202,-0.055901,-0.421657,-0.146694,-0.21647,-0.036395,False,False,False,True,...,False,False,False,False,False,False,True,False,False,11
3264,1.275076,-0.797460,1.131545,0.475976,-0.21647,-0.036395,False,False,False,True,...,False,False,False,False,False,False,True,False,False,9
399,0.028697,-0.135318,-0.033357,-0.146694,4.67372,1.585026,True,False,False,False,...,False,False,False,False,False,False,True,False,False,15
2532,1.421708,-0.717446,1.131545,0.915215,-0.21647,-0.847105,False,False,False,False,...,False,False,False,False,False,False,True,False,False,9

In [ ]:
X_test

,age,fnlwgt,education.num,capital.gain,capital.loss,hours.per.week,Federal-gov,Local-gov,Never-worked,Private,...,Puerto-Rico,Scotland,South,Taiwan,Thailand,Trinadad&Tobago,United-States,Vietnam,Yugoslavia,education
15155,0.981810,-1.198892,1.519846,-0.146694,-0.21647,-0.036395,False,False,False,False,...,False,False,False,False,False,False,False,False,False,12
4281,0.541912,0.257349,-2.751462,-0.146694,-0.21647,-0.036395,False,False,False,True,...,False,False,False,False,False,False,False,False,False,4
31524,-0.044620,-0.204973,-0.033357,-0.146694,-0.21647,0.368961,False,False,False,True,...,False,False,False,False,False,False,False,False,False,15
12686,-0.191252,-0.336759,-0.421657,-0.146694,-0.21647,0.774316,False,False,False,False,...,False,False,False,False,False,False,True,False,False,11
7273,0.908494,0.096450,1.131545,-0.146694,-0.21647,-0.036395,False,True,False,False,...,False,False,False,False,False,False,True,False,False,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15012,0.321962,0.492964,1.519846,-0.146694,-0.21647,-0.036395,False,True,False,False,...,False,False,False,False,False,False,True,False,False,12
13976,1.128443,2.370150,-0.033357,-0.146694,-0.21647,-0.036395,True,False,False,False,...,False,False,False,False,False,False,True,False,False,15
9307,-1.290999,-0.025224,-0.421657,-0.146694,-0.21647,-0.036395,False,False,False,True,...,False,False,False,False,False,False,True,False,False,11
23959,-1.364315,0.067924,-0.809958,-0.146694,-0.21647,-0.036395,False,False,False,True,...,False,False,False,False,False,False,True,False,False,2
4939,0.688544,-0.211825,0.354944,-0.146694,-0.21647,-0.036395,False,False,False,True,...,False,False,False,False,False,False,True,False,False,8

In [ ]:
from sklearn.metrics import classification_report

target_names = ['<=50K','>50K']

In [ ]:
from sklearn.linear_model import LogisticRegression
logistic_regression = LogisticRegression(random_state=0)
logistic_regression.fit(X_train, y_train)

y_pred = logistic_regression.predict(X_test)

print("train score = "+ str(logistic_regression.score(X_train, y_train)))
print("test score = "+str(logistic_regression.score(X_test, y_test)))

print(classification_report(y_test, y_pred, target_names=target_names))

train score = 0.8515117753275193
test score = 0.8497234173325138
              precision    recall  f1-score   support

       <=50K       0.88      0.93      0.90      4916
        >50K       0.74      0.59      0.66      1592

    accuracy                           0.85      6508
   macro avg       0.81      0.76      0.78      6508
weighted avg       0.84      0.85      0.84      6508

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [ ]:
from sklearn import svm
SVM = svm.SVC()
SVM.fit(X_train, y_train)

y_pred=SVM.predict(X_test)

print("train score = "+ str(SVM.score(X_train, y_train)))
print("test score = "+str(SVM.score(X_test, y_test)))

print(classification_report(y_test, y_pred, target_names=target_names))

train score = 0.8520880556302586
test score = 0.8552550706822373
              precision    recall  f1-score   support

       <=50K       0.87      0.95      0.91      4916
        >50K       0.79      0.56      0.65      1592

    accuracy                           0.86      6508
   macro avg       0.83      0.76      0.78      6508
weighted avg       0.85      0.86      0.85      6508

In [ ]:
from sklearn import tree
Decision_tree = tree.DecisionTreeClassifier()
Decision_tree.fit(X_train, y_train)

y_pred=Decision_tree.predict(X_test)

print("train score = "+ str(Decision_tree.score(X_train, y_train)))
print("test score = "+str(Decision_tree.score(X_test, y_test)))

print(classification_report(y_test, y_pred, target_names=target_names))

train score = 0.9999615813131507
test score = 0.8099262446220037
              precision    recall  f1-score   support

       <=50K       0.88      0.87      0.87      4916
        >50K       0.61      0.61      0.61      1592

    accuracy                           0.81      6508
   macro avg       0.74      0.74      0.74      6508
weighted avg       0.81      0.81      0.81      6508

In [ ]:
from sklearn.naive_bayes import BernoulliNB

naive_bayes= BernoulliNB()

naive_bayes.fit(X_train, y_train)

y_pred=naive_bayes.predict(X_test)

print("train score = "+ str(naive_bayes.score(X_train, y_train)))
print("test score = "+str(naive_bayes.score(X_test, y_test)))

print(classification_report(y_test, y_pred, target_names=target_names))

train score = 0.7566176188097891
test score = 0.7578365089121082
              precision    recall  f1-score   support

       <=50K       0.92      0.75      0.82      4916
        >50K       0.50      0.79      0.61      1592

    accuracy                           0.76      6508
   macro avg       0.71      0.77      0.72      6508
weighted avg       0.82      0.76      0.77      6508

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

KNN = KNeighborsClassifier(n_neighbors=2500)

KNN.fit(X_train,y_train)

y_pred=KNN.predict(X_test)

print("train score = "+ str(KNN.score(X_train, y_train)))
print("test score = "+str(KNN.score(X_test, y_test)))

print(classification_report(y_test, y_pred, target_names=target_names))

train score = 0.8114026662568673
test score = 0.8093116164720344
              precision    recall  f1-score   support

       <=50K       0.81      0.97      0.89      4916
        >50K       0.78      0.30      0.44      1592

    accuracy                           0.81      6508
   macro avg       0.80      0.64      0.66      6508
weighted avg       0.81      0.81      0.78      6508

In [ ]:
from sklearn.ensemble import RandomForestClassifier

random_forest = RandomForestClassifier(n_estimators=100, random_state=10)

random_forest.fit(X_train, y_train)

y_pred=random_forest.predict(X_test)

print("train score = "+ str(random_forest.score(X_train, y_train)))
print("test score = "+str(random_forest.score(X_test, y_test)))

print(classification_report(y_test, y_pred, target_names=target_names))

train score = 0.9999615813131507
test score = 0.8526429010448678
              precision    recall  f1-score   support

       <=50K       0.88      0.93      0.91      4916
        >50K       0.74      0.61      0.67      1592

    accuracy                           0.85      6508
   macro avg       0.81      0.77      0.79      6508
weighted avg       0.85      0.85      0.85      6508

In [ ]:
from sklearn.ensemble import AdaBoostClassifier

ada_boost = AdaBoostClassifier(n_estimators=100, random_state=10)

ada_boost.fit(X_train, y_train)

y_pred=ada_boost.predict(X_test)

print("train score = "+ str(ada_boost.score(X_train, y_train)))
print("test score = "+str(ada_boost.score(X_test, y_test)))

print(classification_report(y_test, y_pred, target_names=target_names))

train score = 0.8657651081486035
test score = 0.8630915795943455
              precision    recall  f1-score   support

       <=50K       0.88      0.95      0.91      4916
        >50K       0.78      0.61      0.68      1592

    accuracy                           0.86      6508
   macro avg       0.83      0.78      0.80      6508
weighted avg       0.86      0.86      0.86      6508

In [ ]:
from sklearn.ensemble import BaggingClassifier

bagging=BaggingClassifier(estimator=svm.SVC(), n_estimators=10, random_state=0)

bagging.fit(X_train, y_train)

y_pred=bagging.predict(X_test)

print("train score = "+ str(bagging.score(X_train, y_train)))
print("test score = "+str(bagging.score(X_test, y_test)))

print(classification_report(y_test, y_pred, target_names=target_names))

train score = 0.8523185677513543
test score = 0.854640442532268
              precision    recall  f1-score   support

       <=50K       0.87      0.95      0.91      4916
        >50K       0.79      0.56      0.65      1592

    accuracy                           0.85      6508
   macro avg       0.83      0.75      0.78      6508
weighted avg       0.85      0.85      0.85      6508

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

gradient_boosting = GradientBoostingClassifier(n_estimators=100, random_state=10)

gradient_boosting.fit(X_train, y_train)

y_pred=gradient_boosting.predict(X_test)

print("train score = "+ str(gradient_boosting.score(X_train, y_train)))
print("test score = "+str(gradient_boosting.score(X_test, y_test)))

print(classification_report(y_test, y_pred, target_names=target_names))

train score = 0.8686080909754504
test score = 0.8658574062692072
              precision    recall  f1-score   support

       <=50K       0.88      0.95      0.91      4916
        >50K       0.80      0.60      0.68      1592

    accuracy                           0.87      6508
   macro avg       0.84      0.77      0.80      6508
weighted avg       0.86      0.87      0.86      6508

In [ ]:
from sklearn.model_selection import GridSearchCV

param_grid={'n_estimators': [100, 200, 300],
    'learning_rate': [0.01, 0.05, 0.1]}
gscv=GridSearchCV(estimator=gradient_boosting, param_grid=param_grid, cv=5)

gscv.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=GradientBoostingClassifier(random_state=10),
             param_grid={'learning_rate': [0.01, 0.05, 0.1],
                         'n_estimators': [100, 200, 300]})

In [ ]:
y_pred=gscv.best_estimator_.predict(X_test)
print("Best score: {}".format(gscv.best_score_))
print("Best parameters: {}".format(gscv.best_params_))
print(classification_report(y_test, y_pred, target_names=target_names))

Best score: 0.8709133664215862
Best parameters: {'learning_rate': 0.1, 'n_estimators': 300}
              precision    recall  f1-score   support

       <=50K       0.89      0.95      0.92      4916
        >50K       0.80      0.64      0.71      1592

    accuracy                           0.87      6508
   macro avg       0.85      0.79      0.81      6508
weighted avg       0.87      0.87      0.87      6508

In [ ]:
!pip install joblib

Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (1.4.2)

In [ ]:
import joblib

joblib.dump(gscv.best_estimator_, '/content/model_income_prediction')

['/content/model_income_prediction']

In [ ]:
model=joblib.load('/content/model_income_prediction')
model.predict(X_test)

array([1, 0, 0, ..., 0, 0, 0])